apiVersion: apps/v1
kind: Deployment
metadata:
  name: metro
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metro
  template:
    metadata:
      labels:
        app: metro
    spec:
      containers:
      - name: metro
        image: shivam193/delhi-metro1:latest   # always use latest
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: metro-svc
spec:
  type: NodePort
  selector:
    app: metro
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
